# Generated by Django 6.0.3 on 2026-03-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('mood_score', models.IntegerField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
